# Generated by Django 4.0.3 on 2022-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('timer', models.CharField(choices=[('past', 'PAST'), ('present', 'PRESENT'), ('future', 'FUTURE')], max_length=10, verbose_name='Timer')),
            ],
        ),
    ]
